# prorammed by 117CS0233(Bhupati)

In [1]:
import cv2
img1=cv2.imread('1.jpg')
img2=cv2.imread('2.jpg')
img3=cv2.imread('3.jpg')
img4=cv2.imread('4.jpg')

In [2]:
## These coordinates for river class are directlty copied from the Collecting_Datapoints program
import numpy as np
riv1 = np.array([[ 36, 233],
       [ 45, 237],
       [ 70, 244],
       [ 89, 256],
       [113, 258],
       [140, 260],
       [162, 259],
       [178, 253],
       [189, 248],
       [200, 245],
       [210, 245],
       [223, 246],
       [236, 250],
       [248, 255],
       [260, 260],
       [269, 266],
       [280, 271],
       [289, 281],
       [298, 283],
       [314, 293],
       [327, 298],
       [338, 300],
       [349, 304],
       [365, 303],
       [373, 298],
       [383, 289],
       [389, 284],
       [398, 278],
       [405, 276],
       [417, 268],
       [430, 268],
       [440, 267],
       [447, 267],
       [462, 265],
       [477, 261],
       [493, 255],
       [499, 251],
       [506, 247],
       [514, 242],
       [523, 236],
       [532, 232],
       [535, 230],
       [383, 283],
       [372, 287],
       [352, 291],
       [189, 244],
       [165, 244],
       [188, 242],
       [255, 254],
       [370, 304]])

riv2 = riv1
riv3 = riv1
riv4= riv1

## These coordinates for non-river class are directlty copied from the Collecting_Datapoints program
non1= np.array([[ 38, 216],
       [ 55, 225],
       [ 87, 237],
       [107, 244],
       [122, 241],
       [154, 231],
       [184, 228],
       [229, 233],
       [256, 241],
       [286, 259],
       [302, 267],
       [316, 276],
       [337, 278],
       [372, 271],
       [397, 261],
       [417, 254],
       [433, 252],
       [456, 246],
       [483, 233],
       [501, 224],
       [521, 213],
       [534, 203],
       [534, 185],
       [530, 152],
       [531, 111],
       [507, 152],
       [427, 196],
       [368, 188],
       [327, 180],
       [294, 176],
       [264, 171],
       [211, 175],
       [153, 181],
       [ 97, 166],
       [ 43, 159],
       [ 44, 125],
       [ 96, 122],
       [143, 123],
       [196, 120],
       [273, 120],
       [322, 121],
       [378, 117],
       [425, 106],
       [351, 223],
       [335, 191],
       [264, 245],
       [354, 245],
       [375, 255],
       [361, 178],
       [295, 113],
       [ 36, 252],
       [ 59, 262],
       [ 90, 278],
       [116, 278],
       [136, 281],
       [156, 276],
       [180, 272],
       [198, 270],
       [220, 273],
       [244, 284],
       [260, 291],
       [291, 305],
       [311, 315],
       [336, 322],
       [363, 325],
       [376, 317],
       [388, 308],
       [412, 292],
       [440, 285],
       [479, 278],
       [506, 269],
       [520, 266],
       [529, 285],
       [527, 308],
       [497, 308],
       [483, 358],
       [439, 320],
       [410, 355],
       [347, 340],
       [309, 345],
       [265, 335],
       [211, 325],
       [160, 325],
       [137, 324],
       [ 81, 322],
       [ 54, 320],
       [ 60, 351],
       [ 81, 403],
       [106, 387],
       [143, 417],
       [196, 409],
       [244, 416],
       [265, 438],
       [305, 436],
       [353, 433],
       [383, 454],
       [422, 444],
       [438, 464],
       [474, 458],
       [497, 435]])
non2= non1
non3= non1
non4= non1

# Step 1

In [3]:
#here [r,g,b] is equialent to [r,r,r], since g==r and b==r.
img1[riv1[:,0],riv1[:,1],0]

array([ 94,  96,  87,  93,  94,  89,  97,  93,  85,  84,  88,  93,  81,
        99,  89, 102,  88, 100,  94,  95,  83,  84,  89,  81,  86,  96,
       102,  91,  87,  89,  90,  94,  96,  86,  93,  91,  95,  95, 100,
        96,  98,  96, 104,  99,  99,  92, 105,  95, 102,  79], dtype=uint8)

In [4]:
#Calculating mean of River_Class
T1 = np.array([img1[riv1[:,0],riv1[:,1],0].mean(),img2[riv2[:,0],riv2[:,1],0].mean(),img3[riv3[:,0],riv3[:,1],0].mean(),img4[riv4[:,0],riv4[:,1],0].mean()])
T1

array([ 92.68, 102.18,  91.26,  28.16])

# Step 2

In [5]:
img4[non4[:,0],non4[:,1],0]

array([ 77,  70,  77,  62,  36,  76,  75,  62,  78,  72, 102,  61,  60,
        59,  69,  55,  66,  73,  61,  73,  87,  43,  56,  64,  60,  78,
        66,  81,  83, 119,  84, 106, 119,  84,  86,  91, 110,  93, 110,
        90,  87,  91,  64,  57,  63,  74,  50,  54,  53, 107,  86,  75,
        72,  74,  77,  63,  62,  80,  88,  80,  71,  61,  57,  61,  73,
        50,  61,  54,  54,  62,  94, 148, 116,  60,  62,  59,  60,  53,
        58,  59,  70,  57,  71,  93,  76,  71,  83, 107,  99,  94,  74,
       104, 119,  67,  83,  83,  93, 109, 110,  62], dtype=uint8)

In [6]:
#Calculating mean of NonRiver_Class
T2=np.array([img1[non1[:,0],non1[:,1],0].mean(),img2[non2[:,0],non2[:,1],0].mean(),img3[non3[:,0],non3[:,1],0].mean(),img4[non4[:,0],non4[:,1],0].mean()])
T2

array([71.2 , 71.84, 70.26, 76.29])

# Step 3

In [7]:
#Calculating covarianc_matrix of River_Class
cov_riv=np.cov([img1[riv1[:,0],riv1[:,1],0],img2[riv2[:,0],riv2[:,1],0],img3[riv3[:,0],riv3[:,1],0],img4[riv4[:,0],riv4[:,1],0]])
cov_riv

array([[39.32408163, 27.83428571, 16.39102041, -5.21306122],
       [27.83428571, 36.92612245, 24.60530612, -8.96816327],
       [16.39102041, 24.60530612, 28.68612245, -4.28734694],
       [-5.21306122, -8.96816327, -4.28734694,  6.62693878]])

# Step 4

In [8]:
#Calculating covarianc_matrix of NonRiver_Class
cov_non=np.cov([img1[non1[:,0],non1[:,1],0],img2[non2[:,0],non2[:,1],0],img3[non3[:,0],non3[:,1],0],img4[non4[:,0],non4[:,1],0]])
cov_non

array([[431.51515152, 302.83030303, 315.6040404 ,  85.26464646],
       [302.83030303, 273.71151515, 271.08242424, 145.61252525],
       [315.6040404 , 271.08242424, 351.26505051, 101.82282828],
       [ 85.26464646, 145.61252525, 101.82282828, 393.90494949]])

# Step 5

In [9]:
img1.shape

(598, 676, 3)

In [10]:
##Collecting (512,512,1) test points from four (598, 676, 3) images
test_data=[]
for i in range(512):
    for j in range(512):
        test_data.append([img1[i,j][0],img2[i,j][0],img3[i,j][0],img4[i,j][0]])

test_data[-100000]

[70, 74, 78, 65]

# Step 6

In [11]:
import numpy as np
test_data= np.array(test_data)
test_data.shape

(262144, 4)

In [12]:
test_data

array([[255, 255, 255, 255],
       [255, 255, 255, 255],
       [255, 255, 255, 255],
       ...,
       [ 25,  36,  18,  27],
       [ 21,  36,  16,  27],
       [ 22,  36,  14,  27]], dtype=uint8)

# Step 7 - 14

Given, prior probabilities P1=0.3 and P2=0.7

In [23]:
output=[]
P1 = 0.3
P2 = 0.7

for i in test_data:
    #Step 8
    x=np.array(i-T1)
    inverse=np.linalg.inv(cov_riv)
    river_class = float(np.dot(np.dot(x.reshape(1,4), inverse), x))
    
    #Step 9
    y=np.array(i-T2)
    inverse=np.linalg.inv(cov_non)
    non_class = float(np.dot(np.dot(y.reshape(1,4), inverse), y))
    
    #Step 10 - calculate density funtion for River_Class
    p1= (0.5)*(1/np.sqrt(np.linalg.det(cov_riv)))*np.exp((-0.5)*river_class)
    #Step 11 - calculate density funtion for NonRiver_Class
    p2= (0.5)*(1/np.sqrt(np.linalg.det(cov_non)))*np.exp((-0.5)*non_class)
    
    #Step 11 Applying Baye' Rule and stroring in output_image
    if(P1*p1 >= P2*p2):
        output.append(255)
    else:
        output.append(0)
        
    
output

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [24]:
#reshape the image to required scale (512*512)
output=np.array(output).reshape(512,512)
output

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [25]:
#showing the output_image
import numpy as np
from PIL import Image

img = Image.fromarray(np.uint8(output) , 'L')
img.show()              ##Look into pop up window.

Repeating the above press for another given prior probality P1 = 0.7 and P2 = 0.3

In [26]:
output=[]
P1 = 0.7
P2 = 0.3

for i in test_data:
    #Step 8
    x=np.array(i-T1)
    inverse=np.linalg.inv(cov_riv)
    river_class = float(np.dot(np.dot(x.reshape(1,4), inverse), x))
    
    #Step 9
    y=np.array(i-T2)
    inverse=np.linalg.inv(cov_non)
    non_class = float(np.dot(np.dot(y.reshape(1,4), inverse), y))
    
    #Step 10
    p1= (0.5)*(1/np.sqrt(np.linalg.det(cov_riv)))*np.exp((-0.5)*river_class)
    #Step 11
    p2= (0.5)*(1/np.sqrt(np.linalg.det(cov_non)))*np.exp((-0.5)*non_class)
    
    #Step 11 Baye' Rule
    if(P1*p1 >= P2*p2):
        output.append(255)
    else:
        output.append(0)
        
    
output

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [27]:
output=np.array(output).reshape(512,512)
output

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [28]:
import numpy as np
from PIL import Image

img = Image.fromarray(np.uint8(output) , 'L')
img.show()             ##Look into pop up window.

Doing the same for another given prior probality P1 = 0.5 and P2 = 0.5

In [29]:
output=[]
P1 = 0.5
P2 = 0.5

for i in test_data:
    #Step 8
    x=np.array(i-T1)
    inverse=np.linalg.inv(cov_riv)
    river_class = float(np.dot(np.dot(x.reshape(1,4), inverse), x))
    
    #Step 9
    y=np.array(i-T2)
    inverse=np.linalg.inv(cov_non)
    non_class = float(np.dot(np.dot(y.reshape(1,4), inverse), y))
    
    #Step 10
    p1= (0.5)*(1/np.sqrt(np.linalg.det(cov_riv)))*np.exp((-0.5)*river_class)
    #Step 11
    p2= (0.5)*(1/np.sqrt(np.linalg.det(cov_non)))*np.exp((-0.5)*non_class)
    
    #Step 11 Baye' Rule
    if(P1*p1 >= P2*p2):
        output.append(255)
    else:
        output.append(0)
        
    
output

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 255,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [30]:
output=np.array(output).reshape(512,512)
output

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [31]:
import numpy as np
from PIL import Image

img = Image.fromarray(np.uint8(output) , 'L')
img.show()               ##Look into pop up window.

In [32]:
##EXTRA
## Since (512,512) shape is considered from left most cornor river is coming in the middle of the image.
## The coordinates of choosing the test_data points will change the position of the river in the output image.

test_data=[]
for i in range(70,582):
    for j in range(70,582):
        test_data.append([img1[i,j][0],img2[i,j][0],img3[i,j][0],img4[i,j][0]])

test_data= np.array(test_data)

output=[]
P1 = 0.3
P2 = 0.7

for i in test_data:
    #Step 8
    x=np.array(i-T1)
    inverse=np.linalg.inv(cov_riv)
    river_class = float(np.dot(np.dot(x.reshape(1,4), inverse), x))
    
    #Step 9
    y=np.array(i-T2)
    inverse=np.linalg.inv(cov_non)
    non_class = float(np.dot(np.dot(y.reshape(1,4), inverse), y))
    
    #Step 10 - calculate density funtion for River_Class
    p1= (0.5)*(1/np.sqrt(np.linalg.det(cov_riv)))*np.exp((-0.5)*river_class)
    #Step 11 - calculate density funtion for NonRiver_Class
    p2= (0.5)*(1/np.sqrt(np.linalg.det(cov_non)))*np.exp((-0.5)*non_class)
    
    #Step 11 Applying Baye' Rule and stroring in output_image
    if(P1*p1 >= P2*p2):
        output.append(255)
    else:
        output.append(0)
        
    
output=np.array(output).reshape(512,512)

from PIL import Image

img = Image.fromarray(np.uint8(output) , 'L')
img.show()               ##Look into pop up window.