In [2]:
import cv2
img1=cv2.imread('1.jpg')
img2=cv2.imread('2.jpg')
img3=cv2.imread('3.jpg')
img4=cv2.imread('4.jpg')

In [3]:
img4.shape

(598, 676, 3)

In [5]:
riv1=[]

def mousePoints(event,x,y,flags,params):
    if(event==cv2.EVENT_LBUTTONDOWN):
        print(img4[y,x])                       #pixel values corresponding to the given coordinates.
        riv1.append([y,x])
        

cv2.imshow("4_Riv",img4)
cv2.setMouseCallback("4_Riv",mousePoints)
cv2.waitKey(0)

## Click 50 time inside the River to collect the coordinates of river class

[27 27 27]
[28 28 28]
[28 28 28]
[30 30 30]
[28 28 28]
[29 29 29]
[28 28 28]
[28 28 28]
[29 29 29]
[28 28 28]
[29 29 29]
[29 29 29]
[31 31 31]
[36 36 36]
[29 29 29]
[28 28 28]
[23 23 23]
[24 24 24]
[24 24 24]
[27 27 27]
[33 33 33]
[31 31 31]
[33 33 33]
[27 27 27]
[29 29 29]
[32 32 32]
[27 27 27]
[29 29 29]
[28 28 28]
[28 28 28]
[33 33 33]
[30 30 30]
[28 28 28]
[26 26 26]
[27 27 27]
[26 26 26]
[28 28 28]
[27 27 27]
[28 28 28]
[28 28 28]
[28 28 28]
[28 28 28]
[25 25 25]
[28 28 28]
[27 27 27]
[30 30 30]
[22 22 22]
[27 27 27]
[24 24 24]
[28 28 28]


-1

In [6]:
import numpy as np
riv1=np.array(riv1)
print(riv1.shape)
riv1            ##Copy these coordinates into Assignment1 program for river class.

(50, 2)


array([[ 36, 233],
       [ 45, 237],
       [ 70, 244],
       [ 89, 256],
       [113, 258],
       [140, 260],
       [162, 259],
       [178, 253],
       [189, 248],
       [200, 245],
       [210, 245],
       [223, 246],
       [236, 250],
       [248, 255],
       [260, 260],
       [269, 266],
       [280, 271],
       [289, 281],
       [298, 283],
       [314, 293],
       [327, 298],
       [338, 300],
       [349, 304],
       [365, 303],
       [373, 298],
       [383, 289],
       [389, 284],
       [398, 278],
       [405, 276],
       [417, 268],
       [430, 268],
       [440, 267],
       [447, 267],
       [462, 265],
       [477, 261],
       [493, 255],
       [499, 251],
       [506, 247],
       [514, 242],
       [523, 236],
       [532, 232],
       [535, 230],
       [383, 283],
       [372, 287],
       [352, 291],
       [189, 244],
       [165, 244],
       [188, 242],
       [255, 254],
       [370, 304]])

In [7]:
non1=[]

def mousePoints(event,x,y,flags,params):
    if(event==cv2.EVENT_LBUTTONDOWN):
        print(img4[y,x])               #pixel values corresponding to the given coordinates.
        non1.append([y,x])
        

cv2.imshow("4_Riv",img4)
cv2.setMouseCallback("4_Riv",mousePoints)
cv2.waitKey(0)

## Click 100 time outside the River to collect the coordinates of non-river class.

[77 77 77]
[70 70 70]
[77 77 77]
[62 62 62]
[36 36 36]
[76 76 76]
[75 75 75]
[62 62 62]
[78 78 78]
[72 72 72]
[102 102 102]
[61 61 61]
[60 60 60]
[59 59 59]
[69 69 69]
[55 55 55]
[66 66 66]
[73 73 73]
[61 61 61]
[73 73 73]
[87 87 87]
[43 43 43]
[56 56 56]
[64 64 64]
[60 60 60]
[78 78 78]
[66 66 66]
[81 81 81]
[83 83 83]
[119 119 119]
[84 84 84]
[106 106 106]
[119 119 119]
[84 84 84]
[86 86 86]
[91 91 91]
[110 110 110]
[93 93 93]
[110 110 110]
[90 90 90]
[87 87 87]
[91 91 91]
[64 64 64]
[57 57 57]
[63 63 63]
[74 74 74]
[50 50 50]
[54 54 54]
[53 53 53]
[107 107 107]
[86 86 86]
[75 75 75]
[72 72 72]
[74 74 74]
[77 77 77]
[63 63 63]
[62 62 62]
[80 80 80]
[88 88 88]
[80 80 80]
[71 71 71]
[61 61 61]
[57 57 57]
[61 61 61]
[73 73 73]
[50 50 50]
[61 61 61]
[54 54 54]
[54 54 54]
[62 62 62]
[94 94 94]
[148 148 148]
[116 116 116]
[60 60 60]
[62 62 62]
[59 59 59]
[60 60 60]
[53 53 53]
[58 58 58]
[59 59 59]
[70 70 70]
[57 57 57]
[71 71 71]
[93 93 93]
[76 76 76]
[71 71 71]
[83 83 83]
[107 107 107]
[9

-1

In [8]:
import numpy as np
non1=np.array(non1)
print(riv1.shape)
non1[:100]          #Copy these coordinates into Assignment1 program for non-river class.

(101, 2)


array([[ 38, 216],
       [ 55, 225],
       [ 87, 237],
       [107, 244],
       [122, 241],
       [154, 231],
       [184, 228],
       [229, 233],
       [256, 241],
       [286, 259],
       [302, 267],
       [316, 276],
       [337, 278],
       [372, 271],
       [397, 261],
       [417, 254],
       [433, 252],
       [456, 246],
       [483, 233],
       [501, 224],
       [521, 213],
       [534, 203],
       [534, 185],
       [530, 152],
       [531, 111],
       [507, 152],
       [427, 196],
       [368, 188],
       [327, 180],
       [294, 176],
       [264, 171],
       [211, 175],
       [153, 181],
       [ 97, 166],
       [ 43, 159],
       [ 44, 125],
       [ 96, 122],
       [143, 123],
       [196, 120],
       [273, 120],
       [322, 121],
       [378, 117],
       [425, 106],
       [351, 223],
       [335, 191],
       [264, 245],
       [354, 245],
       [375, 255],
       [361, 178],
       [295, 113],
       [ 36, 252],
       [ 59, 262],
       [ 90,